  version: 2.1
  executors:
    runai-executor:
      docker:
        - image: cimg/go:1.18.2
  
  commands:
    install_project_dependencies:
      steps:
        - checkout
        - run:
            name: "Install project dependencies"
            command: |
              go mod download
              go mod verify

    pre_docker_commands:
      steps:
        - run:
            name: "Docker gcr login"
            command: cat gcr_auth.json | docker login -u _json_key --password-stdin https://gcr.io
        - run:
            name: "Docker Red Hat login"
            command: echo "$REDHAT_DOCKER_PASS" | docker login -u $REDHAT_DOCKER_USER --password-stdin https://registry.redhat.io
        - setup_remote_docker:
            docker_layer_caching: true
  jobs:
    lint:
      executor: runai-executor
      steps:
         - setup_remote_docker:
              docker_layer_caching: true
         - install_project_dependencies
         - run:
             command: |
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
              golangci-lint run -v --timeout 5m
    test:
      executor: runai-executor
      steps:
        - setup_remote_docker:
              docker_layer_caching: true
        - install_project_dependencies
        - run:
            name: "Create a temp directory for artifacts"
            command: |
              mkdir -p /tmp/artifacts
              mkdir -p /tmp/artifacts/test-results
              mkdir -p /tmp/artifacts/test-results/unit-tests
              mkdir -p /tmp/artifacts/test-results/service-tests

        # - run:
        #     name: "Run Unit tests"
        #     command: |
        #       echo "Running Unit tests"
        #       gotestsum --junitfile /tmp/artifacts/test-results/unit-tests/unit-tests.xml -f standard-verbose -- -count 1 -coverprofile=coverageresult.out ./pkg/...
        #       go tool cover -html=coverageresult.out -o coverage.html
        #       mv coverage.html /tmp/artifactse
        - run:
            name: "Run Service tests"
            command: |
              make test-all
        - store_artifacts:
            name: "Store artifacts"
            path: /tmp/artifacts
        - store_test_results:
            name: "Store test results"
            path: /tmp/artifacts/test-results
    deploy_to_staging:
      executor: runai-executor
      steps:
        - checkout
        - run:
            name: "Extract gcloud private key to file"
            command: echo "$STAGING_GCLOUD_SERVICE_JSON_CONTENT" | base64 -d > ./gcr_auth.json
        - pre_docker_commands
        - run:
            name: "Build Images"
            command: |
              TAG=$(git rev-parse main)
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make images DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}
        - run:
            name: "Push to Google Cloud"
            command: |
              TAG=$(git rev-parse main)
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make push-all DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}
    deploy_to_production:
      executor: runai-executor
      steps:
        - checkout
        - run:
            name: "Extract gcloud private key to file"
            command: echo "$STAGING_GCLOUD_SERVICE_JSON_CONTENT" | base64 -d > ./gcr_auth.json

        - pre_docker_commands
        - run:
            name: "Push to Google Cloud"
            command: |
              TAG=${CIRCLE_TAG/v/''}
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make images DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}
              make push-all
  workflows:
    version: 2
    production:
      jobs:
        - lint:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
        - test:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
        - deploy_to_production:
            requires:
              - lint
              - test

            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/

    build_test_deploy:
      jobs:
        # - build:
        #     filters:
        #       tags:
        #         ignore: /^v.*/

        # - lint:
        #     filters:
        #       tags:
        #         ignore: /^v.*/
        # - test:
        #     filters:
        #       tags:
        #         ignore: /^v.*/

        - deploy_to_staging:
            requires:
              - lint
              - test

            filters:
              tags:
                ignore: /^v.*/
              branches:
                only:
                  - RUN-3997/CI-CD
                  # - main