  version: 2.1
  executors:
    runai-executor:
      docker:
        - image: cimg/go:1.18.2
  
  commands:
    remote_docker:
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
            version: 20.10.14
    install_project_dependencies:
      steps:
        - checkout
        - run:
            name: "Install project dependencies"
            command: |
              go mod download
              go mod verify

    pre_docker_commands:
      steps:
        - run:
            name: "Docker gcr login"
            command: cat gcr_auth.json | docker login -u _json_key --password-stdin https://gcr.io
        - run:
            name: "Docker Red Hat login"
            command: echo "$REDHAT_DOCKER_PASS" | docker login -u $REDHAT_DOCKER_USER --password-stdin https://registry.redhat.io
        - run:
            name: "Extract gcloud private key to file"
            command: echo "$STAGING_GCLOUD_SERVICE_JSON_CONTENT" | base64 -d > ./gcr_auth.json
        - remote_docker


    operator_update_version_in_helm_chart:
      steps:
        - run:
            name: Update version in helm chart
            command: |
              TAG=${CIRCLE_TAG/v/''}
              echo "Updating fake-gpu-operator new version number $TAG in runai helm chart directory..."
              cd deploy/fake-gpu-operator
              sed -i "0,/^\([[:space:]]*tag: *\).*/s//\1$TAG/" values.yaml

  jobs:
    lint:
      executor: runai-executor
      steps:
         - remote_docker
         - install_project_dependencies
         - run:
             command: |
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
              golangci-lint run -v --timeout 5m
    test:
      executor: runai-executor
      steps:
        - remote_docker
        - install_project_dependencies
        - run:
            name: "Create a temp directory for artifacts"
            command: |
              mkdir -p /tmp/artifacts
              mkdir -p /tmp/artifacts/test-results
              mkdir -p /tmp/artifacts/test-results/unit-tests
              mkdir -p /tmp/artifacts/test-results/service-tests

        # - run:
        #     name: "Run Unit tests"
        #     command: |
        #       echo "Running Unit tests"
        #       gotestsum --junitfile /tmp/artifacts/test-results/unit-tests/unit-tests.xml -f standard-verbose -- -count 1 -coverprofile=coverageresult.out ./pkg/...
        #       go tool cover -html=coverageresult.out -o coverage.html
        #       mv coverage.html /tmp/artifactse
        - run:
            name: "Run Service tests"
            command: |
              make test-all
        - store_artifacts:
            name: "Store artifacts"
            path: /tmp/artifacts
        - store_test_results:
            name: "Store test results"
            path: /tmp/artifacts/test-results
    deploy_to_staging:
      executor: runai-executor
      steps:
        - checkout
        - pre_docker_commands
        - run:
            name: "Build Images"
            environment:
              CIRCLE_TAG: <<pipeline.git.revision>>
            command: |
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make images DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${CIRCLE_TAG}
        - run:
            name: "Push to Google Cloud"
            command: |
              TAG=<<pipeline.git.revision>>
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make push-all DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}
    deploy_to_production:
      executor: runai-executor
      steps:
        - checkout
        - pre_docker_commands
        - run:
            name: "Push to Google Cloud"
            environment:
              CIRCLE_TAG: <<pipeline.git.tag>>
            command: |
              TAG=${CIRCLE_TAG/v/''}
              DOCKER_REPO_BASE="gcr.io/run-ai-staging/fake-gpu-operator"
              make images DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}
              make push-all DOCKER_REPO_BASE=${DOCKER_REPO_BASE} DOCKER_TAG=${TAG}

  helm_operator_build_staging:
    docker:
      - image: google/cloud-sdk:276.0.0
    steps:
      - checkout
      - remote_docker
      - pre_docker_commands
      - operator_update_version_in_helm_chart
      - run:
          name: "build helm operator for staging"
          environment:
            HELM_URL: https://get.helm.sh
            HELM_TARBALL: helm-v3.7.1-linux-amd64.tar.gz
            RUNAI_REPO_URL: https://fake-gpu-operator.storage.googleapis.com/
          command: |
            echo "Setting up Helm client..."

            curl --user-agent curl-ci-sync -sSL -o "$HELM_TARBALL" "$HELM_URL/$HELM_TARBALL"
            tar xzfv "$HELM_TARBALL"
            PATH="$(pwd)/linux-amd64/:$PATH"

            sed -i "s/CHART_VERSION/0.0.0-$CIRCLE_SHA1/g" deploy/fake-gpu-operator/Chart.yaml
            helm repo add stable https://charts.helm.sh/stable
            helm repo add runai "$RUNAI_REPO_URL"
            helm repo update
            helm dep update .
            
  chart_build_staging:
    working_directory: ~/go/src/github.com/run-ai/fake-gpu-operator
    docker:
      - image: google/cloud-sdk:276.0.0 # Later versions do not have pip
    steps:
      - checkout
      - run:
          name: Package and publish chart to staging
          environment:
            CIRCLE_SHA1: <<pipeline.git.revision>>
            CIRCLE_TAG: <<pipeline.git.tag>>
            PIPELINE_NUMBER: <<pipeline.number>>
            REPO_URL: https://fake-gpu-operator.storage.googleapis.com/
            BUCKET: gs://fake-gpu-operator
            UPLOAD_TARGET: staging
            GCLOUD_PROJECT: run-ai-staging
          command: |
            script/uploadChart.sh

  workflows:
    version: 2
    production:
      jobs:
        - lint:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
        - test:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
        - deploy_to_production:
            requires:
              - lint
              - test
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/  
        - helm_operator_build_staging:
            requires:
              - deploy_to_production
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/

    build_test_deploy:
      jobs:
        - lint:
            filters:
              tags:
                ignore: /^v.*/
        - test:
            filters:
              tags:
                ignore: /^v.*/

        - deploy_to_staging:
            requires:
              - lint
              - test

            filters:
              tags:
                ignore: /^v.*/
              branches:
                only:
                  - main