devicePlugin:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-lab/fake-gpu-operator/device-plugin
    tag: 0.0.1
  resources: {}

statusUpdater:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-lab/fake-gpu-operator/status-updater
    tag: 0.0.1
  resources: {}

statusExporter:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-lab/fake-gpu-operator/status-exporter
    tag: 0.0.1
  resources: {}
  topologyMaxExportInterval: 10s

initialTopology:
  mig-strategy: mixed
  nodes:
    runai-worker:
      gpu-count: 8
      gpu-memory: 11441
      gpu-product: Tesla-K80
    runai-worker2:
      gpu-count: 8
      gpu-memory: 11441
      gpu-product: Tesla-K80